# Generated by Django 4.2.7 on 2026-02-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
