# Generated by Django 4.2.7 on 2026-02-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_package_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='balance_went_negative',
            field=models.BooleanField(default=False),
        ),
    ]
