# Generated by Django 4.2.7 on 2026-02-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_creditcard_balance_order_balance_went_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='api_source',
            field=models.CharField(default='WEB', help_text='Source of the order (WEB, MATIK)', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='external_ref',
            field=models.CharField(blank=True, help_text='Reference ID from external API', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='raw_api_data',
            field=models.TextField(blank=True, help_text='Raw data received from API', null=True),
        ),
    ]
