# Generated by Django 4.2.7 on 2026-02-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_api_source_order_external_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='code',
            field=models.CharField(blank=True, help_text='Package code (Küpür) from API', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('3DS_WAITING', '3DS Waiting'), ('WAITING_MANUAL_ACTION', 'Waiting Manual Action'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=30),
        ),
    ]
