# Generated by Django 4.2.7 on 2026-02-20 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_package_code_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_autonomous_active', models.BooleanField(default=False, help_text='Sistemi açıp kapatma anahtarı')),
                ('default_card', models.ForeignKey(blank=True, help_text='Otomatik işlemlerde kullanılacak varsayılan kart', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.creditcard')),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
            },
        ),
    ]
