# Generated by Django 4.2.7 on 2026-02-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot of the browser at the final moment of the state', null=True, upload_to='order_screenshots/'),
        ),
        migrations.AddField(
            model_name='order',
            name='resolved_package_name',
            field=models.CharField(blank=True, help_text='The exact package name found and clicked by the robot', max_length=200, null=True),
        ),
    ]
